### ISSUE TITLE
Conflicting packages Microsoft.EntityFrameworkCore.SqlServer and Pomelo.EntityFrameworkCore.MySql

### ISSUE THREAD

**Issue by jensschmidbauer** [borisdj/EFCore.BulkExtensions#937] opened 2022-09-02 12:50 UTC
Tested with version 6.5.6
Both packages contain identical extension methods for Microsoft.EntityFrameworkCore.DbFunctions
Both SqlServerDbFunctionsExtensions and MySqlDbFunctionsExtensions use namespace Microsoft.EntityFrameworkCore
Referencing EFCore.BulkExtensions causes a compile error when using these methods.

example code:

```
using Microsoft.EntityFrameworkCore;

var context = new MyDbContext();
var time = context.Entities.FirstOrDefault(x => EF.Functions.DateDiffDay(x.Time, DateTime.Now) < 7);

public class Entity
{
    public DateTime Time { get; set; }
}

public class MyDbContext : DbContext
{
    public DbSet<Entity> Entities { get; set; }
}

```

**Comment by lsiepel** [comment] 2022-09-06 19:21
Have similair issue, for me 6.5.4 was fine, 6.5.5 introduced this problem.
A call to: `EF.Functions.DateDiffSecond`
leads to:
`'Microsoft.EntityFrameworkCore.SqlServerDbFunctionsExtensions.DateDiffSecond(Microsoft.EntityFrameworkCore.DbFunctions, System.DateTime, System.DateTime)' and 'Microsoft.EntityFrameworkCore.MySqlDbFunctionsExtensions.DateDiffSecond(Microsoft.EntityFrameworkCore.DbFunctions, System.DateTime, System.DateTime)'
`

Not sure, but a possible fix could be: https://github.com/borisdj/EFCore.BulkExtensions/pull/942

**Comment by borisdj** [comment] 2022-09-07 07:13
Dupe of https://github.com/borisdj/EFCore.BulkExtensions/issues/669
Check there for current fix with explicit call or alias.

**Closed by borisdj** 2022-09-07 07:13 UTC
Labels: duplicate, question

**Comment by borisdj** [comment] 2022-12-07 12:18
New Structure (as of verion 6.6.0):
| Num | Project | References | NuGet |
| - | - | - | - |
| [0] | EFCore.BulkExtensions                     |      | - |
| [1] | EFCore.BulkExtensions.SQLServer    | [0] | EFCore.BulkExtensions.SQLServer |
| [2] | EFCore.BulkExtensions.PostgreSQL  | [0] | EFCore.BulkExtensions.PostgreSQL|
| [3] | EFCore.BulkExtensions.MySQL         | [0] | EFCore.BulkExtensions.MySQL |
| [4] | EFCore.BulkExtensions.SQLite          | [0] | EFCore.BulkExtensions.SQLite |
| [5] | EFCore.BulkExtensions.Common      | [1,2,3,4] | EFCore.BulkExtensions

[0] | _EFCore.BulkExtensions_ is shared core project that has no Nuget.
Instead project [5] _EFCore.BulkExtensions.Common_ references all other projects thereby includes all providers and it has NuGet with base name: **EFCore.BulkExtensions** to keep full compatibility with previous versions.
