### ISSUE TITLE
EFCore 6.0 support

### ISSUE THREAD

**Issue by angelaki** [borisdj/EFCore.BulkExtensions#632] opened 2021-09-13 23:25 UTC
The latest version _(5.4.0)_ still gives a `method not found exception` for EFCore 6.0. Is support planned?

**Comment by borisdj** [comment] 2021-09-14 06:49
It is planned.
Dupe of https://github.com/borisdj/EFCore.BulkExtensions/issues/485

**Closed by borisdj** 2021-09-14 06:49 UTC
Labels: duplicate

**Comment by angelaki** [comment] 2021-09-14 06:50
Oh, sorry .... Actually didn't find it - eventhough it obviously wasn't hard to find.
