### ISSUE TITLE
Bulk-Update closes an open SqlConnection that leads to "sp_reset_connection"

### ISSUE THREAD

**Issue by PawelGerr** [borisdj/EFCore.BulkExtensions#253] opened 2019-10-31 13:51 UTC
`MergeAsync` or rather `CheckHasIdentityAsync` that is used by `BulkUpdateAsync` is closing the `SqlConnection` previously opened by some other code. This behavior leads to (multiple) executions of `exec sp_reset_connection` that drops temp tables in the middle of a (ASP.NET) request. 

An option could be: Instead of using the `SqlConnection` directly you may use `OpenConnectionAsync` on `context.Database`. Doing that you don't need to check the connection state because [RelationalConnection](https://github.com/aspnet/EntityFrameworkCore/blob/f780a3aef9839131aef118cd73dda625e22fb980/src/EFCore.Relational/Storage/RelationalConnection.cs) is using a counter `_openedCount` internally. So, an open connection stays open and a closed connection will be opened and closed in the end.

```
public async Task CheckHasIdentityAsync( .... )
{
   await context.Database.OpenConnectionAsync().ConfigureAwait(false);

   try
   {
     // content of "CheckHasIdentityAsync" without "sqlConnection.OpenAsync(cancellationToken)"
   }
   finally
  {
     context.Database.CloseConnection();
  }
}
```

I'm using 
* EFCore.BulkExtensions: 2.6.1
* Microsoft.EntityFrameworkCore.SqlServer: 2.2.6

**Comment by borisdj** [comment] 2020-03-29 08:46
Can you try now with latest version.
If the issue repeats write a test where it is reproducible.

**Comment by videokojot** [comment] 2020-04-14 15:37
Hi, I am having issues with transactions being completed by BulkOperations, while it should not be either commited or rolledback, but I cannot understand why it is happening, maybe it is connected to this issue. 

@PawelGerr can I ask you how is the CheckHasIdentityAsync closing the previously opened connection?

**Comment by PawelGerr** [comment] 2020-04-14 15:49
@videokojot There is a pull request for that https://github.com/borisdj/EFCore.BulkExtensions/pull/314
There are multiple places in the code that close the connection, it is not just CheckHasIdentityAsync.
If you want to be sure that your issue has something to do with mine then you can use my fork to check it out: https://github.com/PawelGerr/EFCore.BulkExtensions

**Comment by videokojot** [comment] 2020-04-14 16:43
Thanks, I see what could cause it. I will check it out. But I am calling BulkOperatiosn via wrapper, which opens the transaction everytime, so your fix should not affect mine problem, because it seems, he is not closing connection if there if transaction present. I ll keep diggin.

**Comment by borisdj** [comment] 2020-07-01 22:06
Nuget 3.1.2 published

**Closed by borisdj** 2020-07-01 22:06 UTC
Labels: can't reproduce
