### ISSUE TITLE
Error when updating Entities with different column names

### ISSUE THREAD

**Issue by MoritzMK** [borisdj/EFCore.BulkExtensions#524] opened 2021-04-16 08:34 UTC
Hi guys,

I discovered an issues after upgrading from package version 3.3.1 to 5.0.7.
The names of the properties from the model differ from the column names of the table. This is configured in the EF Configuration.
```csharp
builder.Property(s => s.PropertyA)
    .HasColumnName("ColumnB")
    .IsRequired();

builder
    .Property(s => s.PropertyB)
    .HasColumnName("ColumnB")
    .IsRequired();
```
Then I try to update some entities by with the given bulk config.
```csharp
var bulkConfig = new BulkConfig
{
    BulkCopyTimeout = 240,
    SetOutputIdentity = true,
    PreserveInsertOrder = true,
    BatchSize = 1000,
    UpdateByProperties = new List<string>
    {
        nameof(WorkProcessToLegalUnit.PropertyA),
        nameof(WorkProcessToLegalUnit.PropertyB),
    },
    CalculateStats = true
};

await ((DbContext)_context).BulkUpdateAsync(entities, bulkConfig, null, cancellationToken).ConfigureAwait(false);
```

I receive this error message: Invalid column name 'PropertyA'. Invalid column name 'PropertyB'.
I fixed this error by replacing the property names in the property *PrimaryKeysPropertyColumnNameDict* of the class TableInfowith the column names. 
```csharp
PrimaryKeysPropertyColumnNameDict = AreSpecifiedUpdateByProperties ? BulkConfig.UpdateByProperties.ToDictionary(a => a, b => b)
                                                                               : (primaryKeys ?? new Dictionary<string, string>());

PrimaryKeysPropertyColumnNameDict = AreSpecifiedUpdateByProperties ? BulkConfig.UpdateByProperties.ToDictionary(a => a, b => entityType.GetProperties().First(p => p.Name == b).GetColumnName(ObjectIdentifier))
                                                                               : (primaryKeys ?? new Dictionary<string, string>());
```

 But then I receive another SQL Error. Syntax error near output in the Merge Statement.

I can't provide any further error messages, because we already rolled back to version 3.3.1. We also tried another releases, but 3.3.1 seems to be the last working one.

Regards
Moritz

**Comment by borisdj** [comment] 2021-04-19 14:02
Fixed with v5.0.9
Thx for contrib.

**Closed by borisdj** 2021-04-19 14:02 UTC
Labels: bug

**Comment by MoritzMK** [comment] 2021-04-20 07:03
Hi Boris,

thank you for the fast response. I updated to version 5.0.9 but still got en error:
`Microsoft.Data.SqlClient.SqlException: 'Incorrect syntax near 'OUTPUT'.'`

Here is the failing SQL Statement from version 5.0.9:
```SQL
MERGE [Stammdaten].[ColumnAToColumnB] WITH (HOLDLOCK) AS T
USING (SELECT TOP 1 * FROM [Stammdaten].[ColumnAToColumnBTemp306f52ce] ORDER BY [ColumnA], [ColumnB]) AS S
ON T.[ColumnA] = S.[ColumnA] AND T.[ColumnB] = S.[ColumnB]
OUTPUT INSERTED.[Id], INSERTED.[ColumnA], INSERTED.[ColumnB],
(CASE $action WHEN 'UPDATE' THEN 1 Else 0 END),
(CASE $action WHEN 'DELETE' THEN 1 Else 0 END)
INTO [Stammdaten].[ColumnAToColumnBTemp306f52ceOutput];
```

And here is the working one from version 3.3.1:
```SQL
MERGE [Stammdaten].[ColumnAToColumnB] WITH (HOLDLOCK) AS T
USING (SELECT TOP 1 * FROM [Stammdaten].[ColumnAToColumnBTemp7b0582e8] ORDER BY [ColumnA], [ColumnB]) AS S
ON T.[ColumnA] = S.[ColumnA] AND T.[ColumnB] = S.[ColumnB]
WHEN MATCHED
THEN UPDATE SET T.[ColumnA] = S.[ColumnA], T.[ColumnB] = S.[ColumnB]
OUTPUT INSERTED.[Id], INSERTED.[ColumnA], INSERTED.[ColumnB],
(CASE $action WHEN 'UPDATE' THEN 1 Else 0 END),
(CASE $action WHEN 'DELETE' THEN 1 Else 0 END)
INTO [Stammdaten].[ColumnAToColumnBTemp7b0582e8Output];
```

Looks like the new version misses the `when matchen` part.

Regards
Moritz

**Comment by borisdj** [comment] 2021-04-20 08:03
Can you write code of entity model in order to reproduce the issue.

**Comment by MoritzMK** [comment] 2021-04-22 09:53
I have created an small example project. [https://github.com/MoritzMK/BulkExtensionsErrorDemo](https://github.com/MoritzMK/BulkExtensionsErrorDemo)

**Comment by borisdj** [comment] 2021-04-22 13:04
This use case is somewhat specific since besides PK that is Identity there are only 2 more columns which are FKs and those are configured to be in _UpdateByProperties_.
Update would work if there were others columns to be updated that are not PK.

However Identity column can not be update via regular EF updates, also [SQL does not permit update Identity Column](https://stackoverflow.com/questions/19155775/how-to-update-identity-column-in-sql-server).
Even if _Id_ column would be left in Merge statement then SqlServer would throw exception:
_`Cannot update identity column 'Id'.'`_

**Comment by borisdj** [comment] 2021-04-22 13:48
Even the old version couldn't have make the Update, it could have only passed without exception but empty so no change would be done.
As for the exception will add that.
