### ISSUE TITLE
Lost password in connectionString

### ISSUE THREAD

**Issue by ahnseunghae** [borisdj/EFCore.BulkExtensions#4] opened 2017-06-05 09:48 UTC
BulkInsert method works fine. But BulkInsertOrUpdate throws an exception like below.
```
System.Data.SqlClient.SqlException occurred
  HResult=0x80131904
  Message=Login failed for user 'user'.
  Source=Core .Net SqlClient Data Provider
  StackTrace:
   at EFCore.BulkExtensions.SqlBulkOperation.Merge[T](DbContext context, IList`1 entities, TableInfo tableInfo, OperationType operationType) in C:\Users\llamar\Dropbox\Bapulcorp\Code\bapul-account\src\EFCore.BulkExtensions\SqlBulkOperation.cs:line 81
   at EFCore.BulkExtensions.DbContextBulkTransaction.Execute[T](DbContext context, IList`1 entities, OperationType operationType, BulkConfig bulkConfig) in C:\Users\llamar\Dropbox\Bapulcorp\Code\bapul-account\src\EFCore.BulkExtensions\DbContextBulkTransaction.cs:line 22
   at EFCore.BulkExtensions.DbContextBulkExtensions.BulkInsertOrUpdate[T](DbContext context, IList`1 entities, BulkConfig bulkConfig) in C:\Users\llamar\Dropbox\Bapulcorp\Code\bapul-account\src\EFCore.BulkExtensions\DbContextBulkExtensions.cs:line 15
```
Seems like the reason is `context.Database.GetDbConnection().ConnectionString` returns connectionString without the password.
```
public static void Insert<T>(DbContext context, IList<T> entities, TableInfo tableInfo, Action<double> progress = null, int batchSize = 2000)
{
    var sqlBulkCopy = new SqlBulkCopy(context.Database.GetDbConnection().ConnectionString)
    {
        DestinationTableName = tableInfo.InsertToTempTable ? tableInfo.FullTempTableName : tableInfo.FullTableName,
        BatchSize = batchSize,
        NotifyAfter = batchSize
    };
    sqlBulkCopy.SqlRowsCopied += (sender, e) => { progress?.Invoke(e.RowsCopied / entities.Count); };

    foreach (var element in tableInfo.PropertyColumnNamesDict)
    {
        sqlBulkCopy.ColumnMappings.Add(element.Key, element.Value);
    }
    using (var reader = ObjectReader.Create(entities, tableInfo.PropertyColumnNamesDict.Keys.ToArray()))
    {
        sqlBulkCopy.WriteToServer(reader);
    }
}
```
The reason is that after invoke CheckHasIdentity method, DbContext somehow lost it's password.

```
public void CheckHasIdentity(DbContext context)
{
    int hasIdentity = 0;
    var conn = context.Database.GetDbConnection();
    try
    {
        conn.OpenAsync();
        using (var command = conn.CreateCommand())
        {
            string query = SqlQueryBuilder.SelectIsIdentity(FullTableName, PrimaryKey);
            command.CommandText = query;
            DbDataReader reader = command.ExecuteReader();

            if (reader.HasRows)
            {
                while (reader.Read())
                {
                    hasIdentity = (int)reader[0];
                }
            }
            reader.Dispose();
        }
    }
    finally
    {
        conn.Close();
    }

    HasIdentity = hasIdentity == 1;
}
```

Thanks.

**Comment by borisdj** [comment] 2017-06-05 18:23
I can not reproduce your issue.
Do you have installed System.Data.SqlClient library in the project.
If you don't that's probably the issue so install it.
Otherwise could you make a sample project where the problem is manifesting and zip it on Drive or Dropbox and send a link.

**Comment by ahnseunghae** [comment] 2017-06-07 02:55
It turns out Persist Security Info should be true in ConnectionString.

https://stackoverflow.com/questions/12467335/connectionstring-loses-password-after-connection-open

**Comment by borisdj** [comment] 2017-06-07 06:12
Glad you solved it.
I will close the issue then.

**Closed** 2017-06-07 06:12 UTC

**Comment by kdm1991** [comment] 2022-08-10 07:23
When I am getting a connection string using GetDbConnection() then Lose the password in connectionString.
How to resolve this issue?
