### ISSUE TITLE
Insert only if the entity does not already exists

### ISSUE THREAD

**Issue by API-kernel** [borisdj/EFCore.BulkExtensions#321] opened 2020-04-16 10:55 UTC
I want to insert entities but only those that don't already exist in the database.
I expect property in BulkConfig 
InsertOnlyIfNotExists - let you insert only entities that doesn't already exists.

in addition, I want the method to return the number of affected rows, it will be useful

**Comment by ugumba** [comment] 2020-04-27 23:22
Same here!  Something to the effect of sqlite's INSERT ON CONFLICT IGNORE would be great. Any solution I've seen without custom SQL suffers from race conditions and performance.problems.

**Comment by borisdj** [comment] 2020-06-24 21:51
At the moment you can use BulkInsertOrUpdate if they existing ones are the same, or use BulkRead and then remove those that exist from List before calling BulkInsert.

**Comment by Masus** [comment] 2020-10-28 12:46
Just to add to what @borisdj mentioned. You can get  a InsertIfNotExist behaviour by using the PropertiesToInclude on BulkConfig. You have to add something to it (empty list seems to be ignored) but just add any of the PK (which always will be the same).

This may affect timestamp columns or triggers but will get the IfNotExist behaviour without having to do a BatchRead and calculate it manually.

**Comment by timothydowd** [comment] 2020-12-29 21:36
Any chance you can elaborate on this? - i thought PropertiesToInclude just meant that only certain columns get added to a record, leaving the rest null - I don't understand how this can be used to ensure only records that are unique are added to the db...

**Comment by borisdj** [comment] 2021-03-12 20:19
Now it can be configured with separate PropertiesTo-Include/Exclude-OnUpdate.
More info in the README:

> If we want only to Insert new ones and to skip those that exist in Db then we can use BulkInsertOrUpdate with config `PropertiesToIncludeOnUpdate = new List<string> { "" }`

This was Dupe of: https://github.com/borisdj/EFCore.BulkExtensions/issues/189

**Closed by borisdj** 2021-03-12 20:19 UTC
Labels: duplicate

**Comment by Masus** [comment] 2021-03-15 14:03
@timothydowd : Sorry for the very late reply. You are correct. I could use it as a InsertIfNotExist only because all the default values was actually the ones I wanted. Sorry for the confusion.

**Comment by raysefo** [comment] 2023-06-08 05:32
Any code sample can you share for inserting only if records do not already exist in the database?

**Comment by StanlyLife** [comment] 2023-10-18 08:32
For me `PropertiesToIncludeOnUpdate` did not work: 

```cs
        public async void AddRange(List<X> aci)
        {
            var bulkConfig = new BulkConfig() { PropertiesToIncludeOnUpdate = new List<string> { "" }, PropertiesToIncludeOnCompare = new List<string> { "Unixtime", "Time", "Activity" } };
            db.BulkInsertOrUpdate(aci, bulkConfig);
            db.SaveChanges();
        }
```


```
Npgsql.PostgresException: '42601: syntax error at or near ")"

POSITION: 44'
```

```
Microsoft.EntityFrameworkCore.Database.Command: Error: Failed executing DbCommand (6ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
INSERT INTO "public"."X" () (SELECT  FROM "public"."X047637c7") ON CONFLICT ("Id") DO NOTHING;
Exception thrown: 'Npgsql.PostgresException' in System.Private.CoreLib.dll
An exception of type 'Npgsql.PostgresException' occurred in System.Private.CoreLib.dll but was not handled in user code
42601: syntax error at or near ")"

POSITION: 44
```

**Comment by videokojot** [comment] 2023-10-18 18:50
@StanlyLife I have added test scenario for you issue to MIT fork of this repository (where I fixed multiple issues fixed in original).

GitHub: https://github.com/videokojot/EFCore.BulkExtensions.MIT
NuGet: https://www.nuget.org/packages/EFCore.BulkExtensions.MIT

and following test passes (so I either fixed your issue or  I am unable to replicate).
If you provide failing example I think I can fix it.
``` csharp
     /// <summary>
    /// Covers issue: https://github.com/borisdj/EFCore.BulkExtensions/issues/321
    /// </summary>
    [Theory]
    [InlineData(DbServerType.SQLServer)]
    [InlineData(DbServerType.PostgreSQL)]
    public void BulkInsertOrUpdate_InsertNewOnly(DbServerType dbType)
    {
        var bulkId = Guid.NewGuid();

        var initialItem = new SimpleItem()
        {
            Name = "initial1",
            BulkIdentifier = bulkId,
            GuidProperty = Guid.NewGuid(),
        };

        using (var db = _dbFixture.GetDb(dbType))
        {
            db.SimpleItems.Add(initialItem);
            db.SaveChanges();
        }

        var initialItemId = initialItem.Id;

        // Should be inserted
        var newItem = new SimpleItem()
        {
            Id = 0,
            StringProperty = "insertedByBulk",
            BulkIdentifier = bulkId,
            GuidProperty = Guid.NewGuid(),
        };

        // Should not be updated (since we use insert only new scenario):
        var updatedItem = new SimpleItem()
        {
            Id = initialItemId,
            BulkIdentifier = bulkId,
            Name = "updated by Bulks",
            GuidProperty = Guid.NewGuid(),
        };

        using (var db = _dbFixture.GetDb(dbType))
        {
            var ensureList = new[] { newItem, updatedItem };

            db.BulkInsertOrUpdate(ensureList,
                                  c =>
                                  {
                                      c.PropertiesToIncludeOnUpdate = new() { "" };
                                  });
        }
        
        var allItems = GetItemsOfBulk(bulkId, dbType);

        Assert.Equal(2, allItems.Count);

        var insertedItem = allItems.SingleOrDefault(x => x.GuidProperty == newItem.GuidProperty);
        Assert.NotNull(insertedItem);

        // initial item was not updated:
        var itemWhichWasNotUpdated = allItems.Single(x => x.GuidProperty == initialItem.GuidProperty);
        Assert.Equal(initialItem.Id, itemWhichWasNotUpdated.Id);
        Assert.Equal(initialItem.Name, itemWhichWasNotUpdated.Name);
    }
```
