### ISSUE TITLE
Geometry coordinates reversed when saved to database

### ISSUE THREAD

**Issue by qvsmith** [borisdj/EFCore.BulkExtensions#604] opened 2021-08-04 12:51 UTC
It would appear that the library is reversing the X and Y coordinates when saving geometry to database.

Using bulk extensions (**BulkUpdateAsync**)
![image](https://user-images.githubusercontent.com/1625105/128183072-344e9f16-fb21-4c1e-98cd-a3a72c14814d.png)
![image](https://user-images.githubusercontent.com/1625105/128183327-95c32b65-7c50-4b17-8813-d4cdc258e7f8.png)

Using plain EF Core (**SaveChangesAsync**)
![image](https://user-images.githubusercontent.com/1625105/128183531-cec2f9ef-9722-42d7-a8be-8cb1e1a0c3e2.png)
![image](https://user-images.githubusercontent.com/1625105/128183640-f3e4e5f4-f800-4e2c-8733-7cb6c8aebf93.png)

Any ideas?

I am using the following:
* EFCore.BulkExtensions 3.6.1
* EF Core 3.1.15
* .NET Core 3.1
* MS SQL Server

**Comment by borisdj** [comment] 2021-08-04 13:50
Can you make a test where it would be reproducible.

**Comment by qvsmith** [comment] 2021-08-04 14:02
Hi @borisdj,

Do you mean a test in this project (on the EFCore3.1 branch)?
Or just a repro project under my github account?

**Comment by qvsmith** [comment] 2021-08-04 20:41
Hi @borisdj 

Added reproducible test - see [PR](https://github.com/borisdj/EFCore.BulkExtensions/pull/605/commits/f0a3f5ef3d97bb9e209c845a18f8d1ebcaf7036b)

**Comment by qvsmith** [comment] 2021-08-05 08:26
Hi @borisdj

Found the issue.

In the `SqlServerAdapter` class the `SqlServerBytesWriter` is initialised with `IsGeography = true` [on this line](https://github.com/borisdj/EFCore.BulkExtensions/blob/EFCore3.1/EFCore.BulkExtensions/SQLAdapters/SQLServer/SqlServerAdapter.cs#L523)

Given a point with **X = 52, Y = 13**:

If `IsGeography` is forced to **true** a SQL Server `Geometry` column's coordinates are reversed / swopped.
![image](https://user-images.githubusercontent.com/1625105/128316992-c2ae2ad7-a97a-4015-9147-29d56583aa6b.png)

If `IsGeography` is forced to **false** a SQL Server `Geography` column's coordinates are reversed / swopped.
![image](https://user-images.githubusercontent.com/1625105/128317577-3e3cc83a-733f-409a-b7cf-468428ae767e.png)

The test I've added in PR above correctly fails in both cases.

I will try to contribute in a sensible way here if I can.

**Comment by qvsmith** [comment] 2021-08-05 13:07
@borisdj I've added a [PR](https://github.com/borisdj/EFCore.BulkExtensions/pull/607) with a possible solution. I've also updated the test and can confirm that it passes now.

**Comment by borisdj** [comment] 2021-08-05 14:28
PRs merged.
Thx for contrib.
Additionally I have removed `GeometryPropertiesToMapToSqlGeometryType` that was added since it's not necesarry.
Type can obtained and checked from metadata, take a look at latest commit.
Also test you added passes always, event when I comment new fix ?

**Comment by qvsmith** [comment] 2021-08-05 15:31
Thanks @borisdj!

I didn't know how to get my hands on the underlying spatial types so I thought I needed some construct to differentiate between them.

I can confirm that test fails on my side when I comment out your modified changes.
![image](https://user-images.githubusercontent.com/1625105/128376750-810704b6-e5d5-4ae0-bb3f-71b0d54ae957.png)
![image](https://user-images.githubusercontent.com/1625105/128376835-75be8799-499b-4c29-baef-a6a9c4321e03.png)

Do you know when you will have a NuGet release ready with the next version containing this fix?

PS: This fix probably needs to be applied to the .NET 5 branch too.

**Comment by borisdj** [comment] 2021-08-05 21:28
NuGet 3.6.3 published.
You can make PR with this fix and its test into master branch for EFCore 5.

**Closed** 2021-08-05 21:29 UTC
Labels: bug

**Comment by qvsmith** [comment] 2021-08-06 06:28
Thanks @borisdj! Appreciate the quick turnaround.

Here is the [PR](https://github.com/borisdj/EFCore.BulkExtensions/pull/609) to apply fix to master.
