### ISSUE TITLE
problem with timestamp fields

### ISSUE THREAD

**Issue by ahmad-rahimi** [borisdj/EFCore.BulkExtensions#91] opened 2018-11-01 20:26 UTC
i created an issue earlier on this subject but you closed it without any change.
i think you was not able to reproduce the problem so i created a new suit of test to show the problem

you can find this tests in my fork

https://github.com/ahmad-rahimi/EFCore.BulkExtensions

thank you

**Comment by borisdj** [comment] 2018-11-01 21:56
Have you tried replacing `ulong` with `byte[]` type, as I have written in the last comment of that [issue87](https://github.com/borisdj/EFCore.BulkExtensions/issues/87)

**Comment by ahmad-rahimi** [comment] 2018-11-01 23:06
yes i do.
with byte[] it only work if i set IsConcurrencyToken for the property. but in my case timestamp is not used for Concurrency checking.

in the tests that i created i show all the scenarios including the one which you said and works.

in file tableinfo.cs line 91 where you filter timestamp fields you check  `a => a.IsConcurrencyToken == true` but it's not enough and you should check for database datatype  too

you support conversions in the library so using ulong for timestamp with conversion should be supported too. this is the default EF behavior. and in ef core 2.1 it is the recommended way for filtering rows by timestamp column. 

see this thread for using ulong instead of byte[]
https://github.com/aspnet/EntityFrameworkCore/issues/5936

currently i use byte[] and for filtering i use the casting workaround for it but because my property don't use IsConcurrencyToken it causes error.

also you always return NULL for timestamp field from the OUTPUT but i think it should be returned with real value because it's mark GeneratedOnAddOrUpdate and EF normally do that.

i think in the outputTempTable you should create the field for timestamp column but with varbinary(8) not timestamp data type so it can be field by INSERTED.FieldName clause and when selecting data from outputTempTable cast that field to timestamp

**Comment by borisdj** [comment] 2018-11-02 09:46
I'll take a look when I have time.

**Comment by borisdj** [comment] 2018-11-11 12:50
I have implemented a fix for this.
Try version 2.2.3

**Comment by ahmad-rahimi** [comment] 2018-11-15 09:44
Nice work.

all tests were passed but sadly a new issue was raised.

if the model has a datetime property with the exact name "UpdateDate" an exception will be generated.

if data type in sql is datetime2
**Message: System.Data.SqlClient.SqlException : Operand type clash: timestamp is incompatible with datetime2**

and for datetime field
**Message: System.Data.SqlClient.SqlException : Implicit conversion from data type datetime to varbinary is not allowed. Use the CONVERT function to run this query.**

note that this happens only if property name is "UpdateDate" and having other datetime properties with other names does not produce the error.

it seems that somewhere in the code you are finding timestamps fields by their property name which causes this rare situation.

thanks again for your nice work

**Comment by borisdj** [comment] 2018-11-15 19:36
Could you write modelbuilder config and property ifself definition.

**Comment by borisdj** [comment] 2018-11-16 12:52
Actually it's best if you could open new issue, since it differs from the original issue, and write there detailed example for reproducing it,

**Closed by borisdj** 2018-11-16 12:52 UTC
Labels: bug
