### ISSUE TITLE
EnumToStringConverter value converter not being applied

### ISSUE THREAD

**Issue by sandersaares** [borisdj/EFCore.BulkExtensions#140] opened 2019-01-27 14:22 UTC
I have a colum `public JobState State { get; set; }` confgured with `.Property(row => row.State).HasConversion(new EnumToStringConverter<JobState>());`

That is, the enum values of `JobState` should become strings in the database.

Yet when I bulk insert rows, I see "0" in this fields instead of the string value.

I see that value converters were supposedly added https://github.com/borisdj/EFCore.BulkExtensions/issues/39 but it does not seem to work, at least in this case.

Using 2.3.7 on .NET Core 2.2 with EF Core 2.2.1.

**Comment by borisdj** [comment] 2019-01-30 00:48
Could you write here entire Test how to reproduce the issue.
I have just added it to test project in `EFCoreBulkTestAtypical.InsertWithValueConversion()`:
```C#
entities.Add(new Info { Message = "Msg "+i, ConvertedTime = dateTime, State = JobState.StateA });
```

Defining: `public enum JobState { StateA, StateB }`

Adding property to class `Info`:
`public JobState State { get; set; }`

Configuring Conversion in method `OnModelCreating`:
```C#
mb.Entity<Info>().Property(e => e.State).HasConversion(new EnumToStringConverter<JobState>());
```

And in DB in table **Info** column **State** I get value: "_StateA_";

**Comment by sandersaares** [comment] 2019-02-04 06:11
Looks like it only reproduces on tables with owned entity types.

Use migrations to create database for the code below.

```csharp
using EFCore.BulkExtensions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;
using System.ComponentModel.DataAnnotations;

namespace ConsoleApp18
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var rows = new[]
            {
                new ProductRow
                {
                    Id = Guid.NewGuid(),
                    State = ProductState.Bar,
                    OwnedStuff = new OwnedRow
                    {
                        Something = 123,
                    }
                }
            };

            using (var dc = new DataContext())
            {
                dc.BulkInsert(rows);

                dc.SaveChanges();
            }
        }
    }

    public sealed class ProductRow
    {
        public Guid Id { get; set; }

        public ProductState State { get; set; }

        [Required]
        public OwnedRow OwnedStuff { get; set; }
    }

    [Owned]
    public sealed class OwnedRow
    {
        public int Something { get; set; }
    }

    public enum ProductState
    {
        Foo,
        Bar
    }

    public class DataContext : DbContext
    {
        public DbSet<ProductRow> Product { get; set; }

        public DataContext()
        {
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
                optionsBuilder.UseSqlServer("Server=(local);Database=BulkInsert_Issue_Repro;Trusted_Connection=True;");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            var table = modelBuilder.Entity<ProductRow>();

            table.Property(x => x.State)
                .HasConversion(new EnumToStringConverter<ProductState>());
        }
    }
}
```

Instead of "Bar", you get "1" in the State column.

**Comment by borisdj** [comment] 2019-02-04 15:15
Should now work with version 2.4.0 but for this fix is only for EnumToStringConverter.
When DataTables are used Converters have to be reimplemented and at the moment I am not sure how to read Converters settings from Relational info.
https://github.com/borisdj/EFCore.BulkExtensions/blob/e2eb1e35efccd751d44170a8920f8d8d1c44b6f6/EFCore.BulkExtensions/SqlBulkOperation.cs#L327-L334

**Comment by borisdj** [comment] 2019-03-03 18:13
Converters with DataTable fully supported from v 2.4.1

**Comment by borisdj** [comment] 2019-03-03 22:32
Fixed with v. 2.4.2

**Closed by borisdj** 2019-03-03 22:32 UTC
Labels: bug, enhancement

**Comment by alexb5dh** [comment] 2019-09-17 16:22
Conversion is not considered for `BatchUpdate` with `Where` filter on enum. Would it be possible to implement?

**Comment by brandonsmith86** [comment] 2020-12-09 16:26
This issue seems to be back; using version 3.2.5.  I specify the converter using the pre-defined conversion method documented [here](https://docs.microsoft.com/en-us/ef/core/modeling/value-conversions#pre-defined-conversions).  Records are inserted with integer representation of enum; took quite a few hours of troubleshoting to figure out why my foreign key constraints were failing.  Turned out to be caused by this issue.  I put the same comment in the thread for BulkUpdate, as someone else is seeing the same thing.
