### ISSUE TITLE
Postgresql: PropertiesToInclude doesn't work with BulkUpdate

### ISSUE THREAD

**Issue by geis01** [borisdj/EFCore.BulkExtensions#1006] opened 2022-11-16 09:40 UTC
I'm using BulkUpdate with a BulkConfig object containing a PropertiesToInclude limiting my update to a single ("total") field. But it seems  the generated sql will try to update other fields anyway:

```
23502: null value in column "status" of relation "order" violates not-null constraint

DETAIL: Failing row contains (19853, null, 0, null, 1, null, 0, null, null).
```

EDIT: 

I believe it is related to postgres attempting an insert with a row containing only my two fields (the key and the field I wish to update) - as the not null constraint fails, it seems it never gets to do the "ON CONFLICT .. DO UPDATE" part of the generated sql. If I change the MergeTable method in the SqlQueryBuilderPostgreSql class with a specific OperationType.Update handling, I can get it to work with an update statement. Something like the following:

```
var columnsListEquals = GetColumnList(tableInfo, OperationType.Insert);
var columnsToUpdate = columnsListEquals.Where(c => tableInfo.PropertyColumnNamesUpdateDict.ContainsValue(c)).ToList();

if (operationType == OperationType.Update)
{
	string updateColumns = string.Join(",", columnsToUpdate.Select(col => 
		$"{col.Replace("[","\"").Replace("]","\"")}={tableInfo.FullTempTableName.Replace("[",@"""").Replace("]",@"""")}.\"{col.Replace("[",@"""").Replace("]",@"""")}\"")
	);
	string whereCondition = string.Join(" AND ",
		tableInfo.PrimaryKeysPropertyColumnNameDict.Values.ToList().Select(col => 
			$"{tableInfo.FullTableName.Replace("[",@"""").Replace("]",@"""")}.\"{col.Replace("[",@"""").Replace("]",@"""")}\" = " +
			$"{tableInfo.FullTempTableName.Replace("[",@"""").Replace("]",@"""")}.\"{col.Replace("[",@"""").Replace("]",@"""")}\"")
	);
	q =  $"UPDATE {tableInfo.FullTableName.Replace("[",@"""").Replace("]",@"""")} SET {updateColumns} " +
		 $"FROM {tableInfo.FullTempTableName.Replace("[",@"""").Replace("]",@"""")} {(!string.IsNullOrEmpty(whereCondition) ? "WHERE " : "")}{whereCondition}";
}
```

**Comment by borisdj** [comment] 2023-04-12 15:15
Fix from the merged PR does not work for all cases, in fact _InsertTestPostgreSql_ with it now fails.
I think that maybe there is no need for separate Update handling, instead just to fix this bug in existing code.
But I am not able to reproduce this issue.
In its Test I have changed _configUpdateBy_ to:
```C#
var configUpdateBy = new BulkConfig {
    UpdateByProperties = new List<string> { nameof(Item.Name) },
    PropertiesToInclude = new List<string> { nameof(Item.Name), nameof(Item.Description) },
};
```
And it passes.
Generated Sql is:
```SQL
INSERT INTO [Item] ("Description", "Name") (SELECT "Description", "Name" FROM [ItemTemp1ff40709]) ON CONFLICT ("Name") DO UPDATE SET "Description" = EXCLUDED."Description"
```

**Closed** 2023-04-13 21:54 UTC
