### ISSUE TITLE
MySql support

### ISSUE THREAD

**Issue by saeidbabaei-dev** [borisdj/EFCore.BulkExtensions#875] opened 2022-07-12 07:14 UTC
In our company we need mysql bulk insert, i found this package and decided to add mysql support to this package.

**Comment by borisdj** [comment] 2022-07-12 07:39
Dupe of: https://github.com/borisdj/EFCore.BulkExtensions/issues/553
If you make a PR you can continue discussion there.
Thx for contrib.

**Closed by borisdj** 2022-07-12 07:39 UTC
Labels: duplicate

**Comment by saeidbabaei-dev** [comment] 2022-07-12 08:15
Sure. Thanks.
