### ISSUE TITLE
Testing in UseInMemoryDb EFCore.

### ISSUE THREAD

**Issue by mingyao23** [borisdj/EFCore.BulkExtensions#226] opened 2019-09-17 02:46 UTC
Hello and Good day! is there any work around when using BatchDelete() in UseInMemory in ef core dbcontext?
![InvalidCastException](https://user-images.githubusercontent.com/6753371/65007307-47f2c800-d938-11e9-900d-8900b06b15f7.png)

**Comment by borisdj** [comment] 2019-09-19 08:07
Bulk Tests can not have UseInMemoryDb(usually used for Tests), because InMemoryProvider does not support Relational-specific methods.
You could try using SQLite with In-Memory mode instead, since SQLite is also supported.
Duplicate of https://github.com/borisdj/EFCore.BulkExtensions/issues/24

**Closed** 2019-09-22 07:35 UTC
Labels: question
