### ISSUE TITLE
Implicit conversion from data type nvarchar to varbinary is not allowed

### ISSUE THREAD

**Issue by administersoftware** [borisdj/EFCore.BulkExtensions#1175] opened 2023-06-21 12:38 UTC
Hi,

Since upgrading from 7.1.0 to 7.1.2 I now get the following whenever I try and bulk insert records into one of my SQL tables:

![image](https://github.com/borisdj/EFCore.BulkExtensions/assets/6171720/405567a3-8b97-4aff-abca-72e3f0abd5b3)

Like I said, it works fine in 7.1.0 and I've gone back to this version now, but any ideas on where to look for the issue/fix? From what I see from the SQL generated, 7.1.0 created a tempory table where it uses IsUpdate and IsDelete which are cast at bits, but 7.1.2 is using SqlActionIUD which is cast as a char(1). My table does have a RowStamp which in SQL is a TimeStamp (byte array in C#).

Any pointers gratefully appreciated.

Colin.

**Comment by borisdj** [comment] 2023-06-21 13:32
Can you write a test where the issue would be reproducible.
Or take a look at the Test _TimeStampTest_ and try to alter it for this case.

**Comment by administersoftware** [comment] 2023-06-21 15:32
> Can you write a test where the issue would be reproducible. Or take a look at the Test _TimeStampTest_ and try to alter it for this case.

My dev has produced an example showing the issue, it should be here very soon.

Colin.

**Comment by danielkaczmarek** [comment] 2023-06-21 15:41
Here is a test app in wpf, when you run it and press the save button you will notice the exact same exception reported above. When you change the BulkExtensions version to 7.1.0 and try it again, it will be all fine and the data will be saved.
[WpfApp1.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/11819722/WpfApp1.zip)

**Comment by administersoftware** [comment] 2023-06-21 16:06
Thank you Daniel. @borisdj it will also work if you remain on version 7.1.2 but remove RowStamp from the entity, so it's definitely related to the RowStamp.

**Comment by borisdj** [comment] 2023-06-22 09:39
I have copied the code from this project and made a test and it passes.
So still can't reproduce the issue.
You could try the same and if manage to make it pop up, write the code sample.

**Comment by administersoftware** [comment] 2023-06-22 10:20
But if you run our example app it came up with the error yes? Which is doesn't in 7.1.0 or any version before...

**Comment by borisdj** [comment] 2023-06-22 10:34
Haven't tried it, because in order to debug it, need the source code.
Best to have reproducible test.

**Comment by administersoftware** [comment] 2023-06-22 10:35
The source code is in the example provided.

**Comment by administersoftware** [comment] 2023-06-22 11:01
@borisdj, we have downloaded Master and fixed a small XML issue that stops it from building, and when we remove the nuget package from our test app and reference your project then everything works as expected, with no errors...

**Comment by borisdj** [comment] 2023-06-22 11:06
I have figured the same, seems that the issue was fixed with some latest changes that just are not published yet.
There will be new nuget till end of the week.

**Comment by administersoftware** [comment] 2023-06-22 11:08
@borisdj, if we take the DLL built from your master and place it with our example app then it works as expected.

Look forward to an update, thanks for your time.

**Closed** 2023-06-22 11:09 UTC
Labels: question
