### ISSUE TITLE
Not compatible with efcore 9.0

### ISSUE THREAD

**Issue by zelda1link3** [borisdj/EFCore.BulkExtensions#1624] opened 2024-11-29 12:28 UTC
At this moment efcore.bulkextensions is not compatible with efcore 9.0.

**Comment by borisdj** [comment] 2024-11-29 13:02
Dupe of https://github.com/borisdj/EFCore.BulkExtensions/issues/1605

**Closed by borisdj** 2024-11-29 13:02 UTC
Labels: duplicate
