### ISSUE TITLE
[Bug] Xamarin.iOS build failed with Link Sdk Assembliies

### ISSUE THREAD

**Issue by albilaga** [borisdj/EFCore.BulkExtensions#332] opened 2020-05-04 15:10 UTC
Hello. I am using this project in Xamarin.Forms project but the iOS project will always failed if we are using `Linker Behavior` set to `Link Framework SDKs Only`. 
The error said 
`MTOUCH : error MT2002: Failed to resolve "System.Diagnostics.PerformanceCounter" reference from "System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089"`
 Here is the sample project
[BulkExtTest.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/4575435/BulkExtTest.zip)

**Comment by MartinLeist** [comment] 2020-07-03 11:49
I have the same problem. This came with the update to a version for EFCore 3. I originally used EFCore 2 and an older version of EFCore.BulkExtensions. Since the Update I get the same error as the albilaga . This only is an issue with iOS and does not happen if setting the linker to Link All.

**Comment by MartinLeist** [comment] 2020-07-03 14:04
After loading the code and looking for a solution, I found the reason for this issue. There is a reference to `Microsoft.Data.SqlClient`. After changing this back to `System.Data.SqlClient` like it was used in older builds, the project can be build on iOS again. I have also removed the GitHub Sourcelink NuGet, but I'm not sure if this was necessary.

**Comment by borisdj** [comment] 2020-09-13 22:06
_Microsoft.Data.SqlClient_ is newer, and advise is it to use that one.
https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/

**Comment by MartinLeist** [comment] 2020-09-14 09:04
I understand. I was in contact with Microsoft support about this and they and myself were looking through my project for around a week, but I got desktop dlls in my mobile app every time. The moment I changed the reference to System.Data.SqlClient the app worked again. Microsoft support could not tell me why that was the case. They suggested, Microsoft.Data.SqlClient was not fully compatible yet, but I wasn't able to find anything about that issue online.

For now my project works and I've had to change the code anyway to remove the FastMember usage. I'm not sure what would be the best way to address this, since I also read that Microsoft themselves recommend the new reference. Maybe when the BulkExtensions support removing of FastMember for mobile apps I can try around again and if the problem continues I can make a ticket to Microsoft about this.

**Comment by borisdj** [comment] 2020-09-14 09:12
Yes, as already stated I plan to remove FastMember dependency.
Duplicate of: [Library does not work on Xamari.iOS](https://github.com/borisdj/EFCore.BulkExtensions/issues/367#issuecomment-691926170)

**Closed by borisdj** 2020-09-14 09:12 UTC
Labels: question

**Comment by borisdj** [comment] 2021-04-09 19:20
FastMember was removed but it seems that Microsoft.Data.SqlClient does not work on Xamarin - MonoAndorid (Sqlite).
@MartinLeist Have you had any additional info from Microsoft support in the meantime.
Here is some reference:
https://stackoverflow.com/questions/49246580/xamarin-how-to-update-mono-android-version-to-resolve-dependencies
