### ISSUE TITLE
RFI: Insert if missing, otherwise do nothing.

### ISSUE THREAD

**Issue by kellcomnet2** [borisdj/EFCore.BulkExtensions#189] opened 2019-05-20 02:47 UTC
Is there a way to only insert new rows based on the PK otherwise do nothing?

**Comment by borisdj** [comment] 2019-05-28 22:27
You can use BulkRead to get those that already exists in Db and exclude them from Insert.

**Comment by pjh1974** [comment] 2019-06-27 14:16
@borisdj but using 2 round-trips would not guard against the data changing between the BulkRead and the BulkInsert.  It would be helpful to have a BulkInsertNotExists or similar method that used a MERGE statement to INSERT WHEN MATCHED and do nothing WHEN NOT MATCHED.

**Comment by borisdj** [comment] 2019-06-27 16:43
What is your UseCase scenario for this?
Usually InsertOrUpdate is enough for most cases, and even if doing 2 queries to DB as mentioned it is still done relatively fast so small chance for conflict. Since you do not want to update existing only issue could be if some row would be deleted in between queries and then it not being inserted again.
Is this case likely to happen?

**Comment by kellcomnet2** [comment] 2019-06-27 16:44
In my case I insert the record with a Created_DT column with the update it overwrites the date each time.

**Comment by borisdj** [comment] 2019-06-27 23:14
Even then BulkRead can be used to set Created_DT column to value from DB so that it remains the same.

**Comment by pjh1974** [comment] 2019-06-28 10:28
Take the scenario where a process outputs a number of items which it persists to the database, these items can then be modified by the user.  Then, when the process is re-run it generates some of the old items again and also generates new items.  In order to create the new items and not overwrite/update the existing items (which may have user edits), I need to persist the new set, ignoring any rows that already exist.  

As you say this could be achieved by doing a BulkRead followed by a BulkInsert of only the items that were not returned by the BulkRead.  However, any new items added by another process between the calls to BulkRead and BulkInsert would cause the BulkInsert to fail due to a duplicate key violation, if the item happened to be a duplicate of one in the set to update.  The only solution would be to re-run the whole BulkRead, BulkInsert process again; which with large data sets would be costly.  

If I were solving this problem directly in SQL, I would implement it using a MERGE statement or using several INSERT statements, each with a where not exists check.

**Comment by ralefire** [comment] 2019-07-02 22:14
I would generalize the issue to include control over the merge operation "WHEN NOT MATCHED BY TARGET," "WHEN MATCHED," and "WHEN NOT MATCHED BY SOURCE." In my case I want to soft delete rows by updating a database column instead of actually deleting on the merge command "WHEN NOT MATCHED BY SOURCE." A fluent API for strongly typed objects that controls the merge operation would be excellent.

**Comment by kellcomnet2** [comment] 2019-09-04 14:51
Just chiming in that @ralefire proposed approach would be perfect in my opinion.

**Comment by jwisener** [comment] 2019-10-09 21:33
Agree with @ralefire , too bad this is not there. Could have used this library. I have a situation where I need this exact control.

**Comment by jarszkutn** [comment] 2019-12-17 10:44
The similar I proposed some time ago in #155
It would be really helpfull option.

**Comment by borisdj** [comment] 2021-03-12 20:07
This can now be configued with separate PropertiesTo-Include/Exclude-OnUpdate.
More info in the README.

**Closed by borisdj** 2021-03-12 20:07 UTC
Labels: enhancement, question
