### ISSUE TITLE
SqlServer adapter not found 

### ISSUE THREAD

**Issue by pchriste24** [borisdj/EFCore.BulkExtensions#1042] opened 2022-12-20 20:54 UTC
https://github.com/borisdj/EFCore.BulkExtensions/blob/3bc41acf315b5eaf8145d4b2c1459f31d84b25e9/EFCore.BulkExtensions/SqlAdapters/SqlAdaptersMapping.cs#L75

I believe the type name that you are looking for should be 

`Type.GetType(EFCoreBulkExtensionsSqlAdaptersTEXT + ".SqlServer.SqlServerDbServer")`

I have the EFCore.BulkExtensions.SqlServer nuget package installed and if I change the name of the adapter like I suggested above then my bulk operation is successful. Without this change it fails reading the Value Generation Strategy here: 

`string name = SqlAdaptersMapping.DbServer.ValueGenerationStrategy;`

**Comment by rafalFurman** [comment] 2022-12-22 12:17
I just came to the same conclusion while debugging this issue:
![image](https://user-images.githubusercontent.com/5636099/209132312-824df5df-39ea-45f4-90a5-9219ed6fd232.png)

why you do not use  dbServerType = typeof(SqlServerDbServer);  here? to would be resilient to class renames.

**Comment by EqunoxKanashi** [comment] 2022-12-22 15:58
V6.6.4 seams to work still

**Comment by EqunoxKanashi** [comment] 2022-12-22 16:01
or just change the name ".SqlServer.SqlDbServer" to ".SqlServer.SqlServerDbServer"
![image](https://user-images.githubusercontent.com/25562956/209173789-446c09ea-328c-47dd-a538-0b6670a80886.png)

**Comment by sommmen** [comment] 2022-12-23 11:01
Dupe #1040 

Downgrade to v6.6.2 and wait for dev to release new nuget packages.

**Comment by xuexiaoxuan** [comment] 2022-12-23 14:55
and   Microsoft.EntityFrameworkCore   Downgrade to 6.0.12

**Comment by edokan** [comment] 2023-01-03 11:03
duplicate of #1040, fixed in #1039

**Comment by rafalFurman** [comment] 2023-01-03 11:17
this is not fixed if you follow 
https://github.com/borisdj/EFCore.BulkExtensions/blob/3bc41acf315b5eaf8145d4b2c1459f31d84b25e9/EFCore.BulkExtensions/SqlAdapters/SqlAdaptersMapping.cs#L75

                    dbServerType = Type.GetType(EFCoreBulkExtensionsSqlAdaptersTEXT + ".SqlServer.SqlDbServer");

and this

https://github.com/borisdj/EFCore.BulkExtensions/blob/65aebbddb870f78a56bf6cf54ec03208a5821ac0/EFCore.BulkExtensions/SqlAdapters/SqlServer/SqlServerDbServer.cs#L9

public class SqlServerDbServer : IDbServer

you will see the error in current head commit.

**Comment by edokan** [comment] 2023-01-03 12:39
Hello @rafalFurman ,

You refer to a commit. but if you look at the latest commit you will find the file is updated with correct class name

https://github.com/borisdj/EFCore.BulkExtensions/blob/65aebbddb870f78a56bf6cf54ec03208a5821ac0/EFCore.BulkExtensions/SqlAdapters/SqlAdaptersMapping.cs#L75

**Comment by rafalFurman** [comment] 2023-01-03 14:07
hm, Ok when do you plan to release new nuget version as this error is reproducible in 6.4.4?

**Comment by borisdj** [comment] 2023-01-05 21:16
v6.6.5

**Closed by borisdj** 2023-01-05 21:16 UTC
