### ISSUE TITLE
Bulk Insert failes on Geography type

### ISSUE THREAD

**Issue by adamsosinski** [borisdj/EFCore.BulkExtensions#181] opened 2019-05-06 10:45 UTC
Hi,

I'm trying to use a bulk insert with spatial data in asp.net core 2.2 application. 
With the use of Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite extension It allows mapping IPoint type to Geography type in SQL Server DB for a single insert. But it throws the following exception when using the BulkExtension method:

```
The given value of type Point from the data source cannot be converted to type udt of the specified target column.
```

If it can be of any help, from SQL Server Profiler it looks like it is mapping geography column to varbinary(max) for a temporary table.

Not sure if I have missed something on the configuration for bulk insert or spatial support is not implemented.

Also below is my BulkConfig

``` c#
_defaultBulkConfig = new BulkConfig
{
    PreserveInsertOrder = true,
    SetOutputIdentity = true,
    SqlBulkCopyOptions = System.Data.SqlClient.SqlBulkCopyOptions.CheckConstraints,
    TrackingEntities = true
};
```

I will really appreciate any assistance on this.

**Comment by borisdj** [comment] 2019-05-06 11:10
Not yet supported.
Duplicate of: [Geometry , Geography #88](https://github.com/borisdj/EFCore.BulkExtensions/issues/88)

**Closed by borisdj** 2019-05-06 11:10 UTC

**Comment by Anilkumarsingh2001** [comment] 2020-08-27 22:07
not supported yet. I used a workaround by creating an intermediate table in destination database with Nvarchar(max) datatype.

**Comment by miloszskalecki** [comment] 2021-02-25 13:23
I managed to implement a fix using TableInfo:
https://github.com/borisdj/EFCore.BulkExtensions/issues/88#issuecomment-785884799
