### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: 'The given key 'Operator' was not present in the dictionary.'

### ISSUE THREAD

**Issue by danielkaczmarek** [borisdj/EFCore.BulkExtensions#676] opened 2021-12-03 12:48 UTC
Hi,

Until now I was using Z.EntityFramework.Extensions.EFCore, and the only function out of it I used was BulkSaveChangesAsync. I tried yours now but this same method gives me the above exception. In my real application I call UpdateRange on the context and pass in the entities list. The entities passed to it can have a different tracking states, So I just call an extension method that updates the ChangeTracker.Entries with the states each entry should have and then I just call BulkSaveChangesAsync. But I’m getting an exception in your extension and I can't work out why. The code looks like this 

`       var myContext = CreateDb();
        var units = new List<Unit>();
        for (var i = 0; i < 10; i++)
        {
            units.Add(new Unit() {  OperatorId = 1 });
        }
        myContext.UpdateRange(units);
        foreach (var entity in myContext.ChangeTracker.Entries())
        {
            entity.State = EntityState.Added;
        }
        myContext.BulkSaveChanges();
`

I've created a demo app to reproduce it. Any idea of what should I do to make it work ? I know I can call a relevant method on each entry, so an insert when its added, update for modified record etc. But I'll rather stick with the way I was doing it, as it seems easier to do so and saves me from dealing with different entity types.

Thank you
Daniel

[WpfApp1.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/7650445/WpfApp1.zip)

**Comment by borisdj** [comment] 2021-12-03 20:37
Should be fixed now with v6.1.3

**Closed** 2021-12-03 23:55 UTC
Labels: bug

**Comment by danielkaczmarek** [comment] 2021-12-06 11:28
Thank you very much for a quick reply and fix.

This error has stopped but I ran into another two. I managed to reproduce one of them. Basically Im trying to add operator and units at the same save. SaveChanges works fine however BulkSaveChanges throws this SqlException: Incorrect syntax near ')'.

[WpfApp1.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/7660239/WpfApp1.zip)

The other issue I dont know how to reproduce but it gives me  "Parameter count mismatch.", here is the call stack

"   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at EFCore.BulkExtensions.Helpers.GenericsHelpers.GetPropertiesDefaultValue[T](T value, Type type)\r\n   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at EFCore.BulkExtensions.Helpers.GenericsHelpers.GetPropertiesWithDefaultValue[T](IEnumerable`1 values, Type type)\r\n   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__5`1.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at EFCore.BulkExtensions.SQLAdapters.SQLServer.SqlOperationsServerAdapter.<MergeAsync>d__4`1.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at EFCore.BulkExtensions.SqlBulkOperation.<MergeAsync>d__5`1.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at EFCore.BulkExtensions.DbContextBulkTransaction.<ExecuteAsync>d__1`1.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at EFCore.BulkExtensions.DbContextBulkTransactionSaveChanges.<InvokeBulkMethod>d__3.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at EFCore.BulkExtensions.DbContextBulkTransactionSaveChanges.<SaveChangesAsync>d__2.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at EFCore.BulkExtensions.DbContextBulkTransactionSaveChanges.<SaveChangesAsync>d__2.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at EFCore.BulkExtensions.DbContextBulkTransactionSaveChanges.<SaveChangesAsync>d__1.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at EFCore.BulkExtensions.DbContextBulkTransaction.<ExecuteAsync>d__1`1.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at MAUnitOfWork.UnitOfWorkBase.<BulkSaveAsync>d__3.MoveNext() 

Regards
Daniel

**Comment by sumanTitan** [comment] 2022-06-17 17:16
@borisdj  this issue seems to be present after v6.2.
I see it fixed in v6.1.9 but reproduced in other version including the latest.

**Comment by borisdj** [comment] 2022-06-18 15:19
v6.2 compared to v.6.1.9 had change only in PG segment.
Also initial example passes in the test I just tried.
Can you write entire test where the issue you are having would be reproducible.

**Comment by sumanTitan** [comment] 2022-06-21 19:18
@borisdj  Ah I am sorry I thought this was a Postgres thread. I am having issue with postgres using an owned entity type with postgres. It seems to work for 6.1.9 but not for 6.2.0.

It throws `The given key 'Operator_OperatorId' was not present in the dictionary`
[Psql-keynotfound.zip](https://github.com/borisdj/EFCore.BulkExtensions/files/8952168/Psql-keynotfound.zip)
 
Should I create a new issue?
