### ISSUE TITLE
6.5.5 update causes ambiguous call compiler issues

### ISSUE THREAD

**Issue by slubowsky** [borisdj/EFCore.BulkExtensions#898] opened 2022-07-22 13:15 UTC
After updating from 6.5.4 to 6.5.5 get new errors

`Error	CS0121	The call is ambiguous between the following methods or properties: 'Microsoft.EntityFrameworkCore.SqlServerDbFunctionsExtensions.DateDiffDay(Microsoft.EntityFrameworkCore.DbFunctions, System.DateTime?, System.DateTime?)' and 'Microsoft.EntityFrameworkCore.MySqlDbFunctionsExtensions.DateDiffDay(Microsoft.EntityFrameworkCore.DbFunctions, System.DateTime?, System.DateTime?)'`

also similar for DateDiffHour

My project does not use MySql...

**Comment by borisdj** [comment] 2022-07-22 13:23
DUPE of https://github.com/borisdj/EFCore.BulkExtensions/issues/669
You can find there several ways of mitigation the issue, until provider specific version gets separated.

**Closed by borisdj** 2022-07-22 13:23 UTC
Labels: duplicate
